@startuml

class Juego {
    +Actualizar()
    +Iniciar()
    +Finalizar()
}
class Jugador {
    +Mover()
    +Vivir()
    +Perder()
}
class Nivel {
    +Cargar()
    +Reiniciar()
}
class Medicina {
    +Rotar()
    +Caer()
    +Destruir()
}
class Bloque {
    +Romper()
    +Caer()
}
class Virus {
    +Mostrar()
    +Destruir()
}
class Contador {
    +Sumar()
    +Restar()
}
class Tiempo {
    +Contar()
    +Pausar()
}
class Movimiento {
    +Mover()
    +Detener()
}
class Velocidad {
    +Aumentar()
    +Disminuir()
}
class Colision {
    +Detectar()
    +Resolver()
}
class Color {
    +Asignar()
}

class Puntuacion {
    +Sumar()
    +Reiniciar()
}
class Tablero {
    +Cargar()
    +Actualizar()
}
class Entrada {
    +LeerTeclas()
}
class Item {
    +Usar()
}
class PowerUp {
    +Activar()
}
class Ranking {
    +Guardar()
    +Mostrar()
}
class Configuracion {
    +CambiarOpcion()
}
class Partida {
    +Guardar()
    +Cargar()
}

class MemoriaJuego  {
    +Iniciar()
    +Pausar()
    +Finalizar()
}
class MemoriaNivel  {
    +Completar()
    +Reiniciar()
}
class MemoriaJugador  {
    +Vivir()
    +Perder()
    +Mover()
}
class MemoriaMedicina  {
    +Destruir()
    +Caer()
    +Rotar()
}
class MemoriaVirus  {
    +Activo()
    +Destruir()
}
class MemoriaBloque {
    +Romper()
    +Caer()
}
class MemoriaMovimiento  {
    +Iniciar()
    +Detener()
}
class MemoriaPuntuacion  {
    +Guardar()
    +Resetear()
}


Jugador --|> Juego
Item <|-- PowerUp


Juego *-- Jugador
Juego *-- Nivel
Juego *-- Tiempo
Juego *-- Contador
Juego *-- MemoriaJuego
Juego *-- MemoriaPuntuacion
Juego *-- Tablero
Juego *-- Configuracion
Juego *-- Partida
Juego *-- Entrada

Jugador *-- Medicina
Jugador o-- Movimiento
Jugador *-- MemoriaJugador

Medicina o-- Movimiento
Medicina *-- Bloque
Medicina *-- "3" Color
Medicina *-- MemoriaMedicina

Virus *-- Bloque
Virus *-- "3" Color
Virus *-- MemoriaVirus
Virus o-- Colision

Nivel o-- Contador
Nivel *-- Tiempo
Nivel *-- Velocidad
Nivel *-- MemoriaNivel
Nivel *-- Tablero

Movimiento o-- Colision
Movimiento *-- MemoriaMovimiento

Bloque o-- Colision
Bloque *-- MemoriaBloque

Contador *-- Virus
Contador *-- Medicina
Contador *-- Nivel
Contador *-- Jugador
Contador *-- Puntuacion

Tiempo *-- Movimiento
Tiempo *-- Colision

Puntuacion *-- Ranking
Puntuacion *-- MemoriaPuntuacion

Tablero *-- Item

@enduml
